path: /home/csmith/Desktop/School/Winter 2024/Winter Project/ws/Winter-Project/yolo_model/tello_arrow_model/code - colored/data # dataset root dir
train: images/train # train images (relative to 'path')
val: images/test # val images (relative to 'path')

# Classes
names:
  0: down
  1: right
  2: left
  3: up
